### ISSUE TITLE
Mặt éo có thiện cảm

### ISSUE THREAD

**Issue by VUHAILAM** [quang2002/PE-PRF192#1]
Please remove your face in Readme.md

**Comment by Tamkien** [comment]
Đúng vậy

**Comment by quang2002** [comment]
Hi VUHAILAM and Tamkien,

Thank you for bringing this issue to my attention. I've carefully reviewed it and, unfortunately, I won't be able to address this problem for the following reasons:

1. Vì tôi thấy tôi đẹp trai vã ò.
2. Còn 2 bạn thì xấu trai

I understand your concerns, and I value your feedback. If you have any other questions or run into different issues in the future, please don't hesitate to let me know, and I'll do my best to assist you.

Thank you for your understanding and support.

Best regards,
Quang.

**Comment by 2003quynh** [comment]
> Hi VUHAILAM and Tamkien,
> 
> Thank you for bringing this issue to my attention. I've carefully reviewed it and, unfortunately, I won't be able to address this problem for the following reasons:
> 
> 1. Vì tôi thấy tôi đẹp trai vã ò.
> 2. Còn 2 bạn thì xấu trai
> 
> I understand your concerns, and I value your feedback. If you have any other questions or run into different issues in the future, please don't hesitate to let me know, and I'll do my best to assist you.
> 
> Thank you for your understanding and support.
> 
> Best regards, Quang.

In my opinion, LAMVH nói đúng r đấy
